[package]
name = "secrets-manager-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.49.0"
aws-sdk-secretsmanager = "0.19.0"
tokio = { version = "1", features = ["full"] }
